kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
  - name: sonarqube
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - sonar-scanner -Dsonar.projectKey=MSPR-PayeTonKawa_gestionProduits_6a51ba9b-8fec-4730-92cf-8bad2f1f2504 -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

  - name: test
    image: node
    commands:
    - npm install
    - npm test

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      repo: registry.germainleignel.com/paye-ton-kawa/gestion-produits
      registry: registry.germainleignel.com

  - name: msg status
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: "{{#success build.status}}✅{{else}}❌{{/success}}  Repository `[{{repo.name}}/{{commit.branch}}]` triggered by event `[{{uppercase build.event}}]` for build.\n    - Commit [[{{commit.sha}}]({{commit.link}})]\n    - Author `[{{commit.author}} / {{commit.email}}]`\n    - Message: {{commit.message}}    - Drone build [[#{{build.number}}]({{build.link}})] reported `[{{uppercase build.status}}]` at `[{{datetime build.finished \"2006.01.02 15:04\" \"\"}}]`\n"
    when:
      status: [success, failure, changed]

trigger:
  branch:
    - main
