services:
  gestion-produits:
    container_name: gestion-produits
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:3000"
    env_file:
      - .env
    depends_on:
      - db-produits
    networks:
      - payetonkawa-n

  db-produits:
    container_name: db-produits
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - payetonkawa-n

volumes:
  db-data:

networks:
  payetonkawa-n:
    external: true