name: gestion-produits
services:
  app:
    build: .
    ports:
      - 3002:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db-produits
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
