kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build
      - docker build -t registry.germainleignel.com/gestion-produits:${DRONE_COMMIT_SHA} .

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.germainleignel.com
      repo: registry.germainleignel.com/gestion-produits
      tags: ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

# Optionally, you can add a cleanup step to remove the image after pushing
  - name: cleanup
    image: docker:git
    commands:
      - docker rmi registry.germainleignel.com/gestion-produits:${DRONE_COMMIT_SHA}

trigger:
  event:
    - push
    - tag
    - deployment