apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-produits-deployment
  namespace: payetonkawa-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-produits
  template:
    metadata:
      labels:
        app: gestion-produits
    spec:
      containers:
      - name: gestion-produits-container
        image: registry.germainleignel.com/paye-ton-kawa/gestion-produits:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: gestion-produits-secrets
        env:
        - name: ENV
          value: "production"
        - name: DATABASE_HOST
          value: "db-produits.payetonkawa-prod.svc.cluster.local"
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: gestion-produits-secrets
              key: DATABASE_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: gestion-produits-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gestion-produits-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: gestion-produits-secrets
              key: POSTGRES_DB
        - name: KAFKA_BROKERS
          value: "kafka.payetonkawa-prod.svc.cluster.local:9092"
        - name: KAFKA_CONSUMER_GROUP
          valueFrom:
            secretKeyRef:
              name: gestion-produits-secrets
              key: KAFKA_CONSUMER_GROUP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"